### ISSUE TITLE
php warning

### ISSUE THREAD

**Issue by mibuthu** [raohmaru/default-gravatar-sans#1]
When using this plugin I get the following php notice:
`PHP Notice:  Undefined index: found_avatar in /path/to/wordpress/wp-content/plugins/default-gravatar-sans/default-gravatar-sans.php on line 93`

If I look at the code I can find `found_avatar` only in this if statement and nowhere else.

Can you please check?

**Comment by raohmaru** [comment]
Hi @mibuthu,

`found_avatar` is added by `get_avatar_data()` in /wp-includes/link-template.php. I'm not sure why do you get the error, but since the variable is not needed in the plugin I've removed the condition (see commit
https://github.com/raohmaru/default-gravatar-sans/commit/9cbb501f38e412d782af8fd1d0058e94a8a713c3).

Please update the plugin in your WordPress dashboard or download the updated version from [here](https://github.com/raohmaru/default-gravatar-sans/releases/tag/1.1.2).
